.Dd September 2026
.Dt COT 5
.Os cotton 0.1
.Sh NAME
.Nm cot
.Nd the cot programming language

.Sh DESCRIPTION

cot is a small (both in size and features) general-purpose stack concatenative 
programming language 

cot's development is being made side by side with cotton's development, as such, one keeps
the other in mind

cotton has two types of keywords: builtins and immediates

.Bl -tag -width "Immediates"
.It Builtins
Words that are executed at runtime that directly manipulate the data stack or the memory (such as +, -, dup, swap, ->, @, etc.).
.It Immediates
Words processed at compile time to handle control flow and the program's structure (such as if, else, end, etc.).
.El

.Sh WORDS
.Bl -tag -width "-> (slot)"
.It Ic + , - , * , /
Pops two values, performs arithmetic, and pushes the result.
.It Ic dup
Duplicates the top value on the stack.
.It Ic swap
Swaps the top two values on the stack.
.It Ic drop
Discards/drops the top value on the stack.
.It Ic ->
Pops a value and a slot index, then stores the value in that same variable slot.
.It Ic @
Pops a slot index and pushes the stored value back onto the stack.
.It Ic ? if
Pops a value, if it's not zero, then it executes the block after it.
.It Ic else
Executes if the prior if evaluated to zero.
.It Ic end
Closes an if or else block.
.El

NOTE: some of the commands above are subject to change given that cot(ton) has yet to reach it's first stable release - even then, any update to any command will be doccumented here and i will also do my best to not break the whole syntax every update ;w;

.Sh SEE ALSO
.Xr cotton 1

