.Dd September 2026
.Dt COTTON 1
.Os cotton 0.2
.Sh NAME
.Nm cotton
.Nd a tiny stack machine for the cot programming language 

.Sh SYNOPSIS
.Nm
.Ar file.cot

.Sh DESCRIPTION

cotton is a small stack machine for the cot(5) programming language (inspired by Lua, Forth and Uxntal) written in C99

as of now it only compiles cot programs, but, i do intend to add the option to compile cot programs to uxntal in the future :P

.Sh SEE ALSO
.Xr cot 5


