.Dd July 2026
.Dt EIKI 5                                                                 
.Os cotton 0.2
.Sh NAME
.Nm eiki
.Nd the bitmap font for cotton

.Sh DESCRIPTION

eiki is the custom 6x8 bitmap font used by cotton(1) for text rendering. 

there isn't a whole lot to say here ermmm,..,

.Sh SEE ALSO
.Xr cotton 1 ,
.Xr cot 5 ,
.Xr eikimaker 1
